### ISSUE TITLE
Filter by ecosystem

### ISSUE THREAD

**Issue by Callum-A** [steakwallet/airdrops#11]
Currently we list network, I believe it would be a good feature to also add ecosystem to allow filtering on this. For example as an ATOM holder I would like to see only Cosmos airdrops, you can currently achieve this through network filters but adding ecosystem allows another layer of filtering.

I am happy to do the work on this one.

**Comment by AlexBHarley** [comment]
Hey @Callum-A! I agree ecosystem filtering would be nice. 

Is your thought to group EVM compatible chains and IBC enabled ones?

**Comment by Callum-A** [comment]
Supporting a list would be ideal so in the JSON say for example Evmos does an EVM and IBC airdrop the layout would be
`{
    "ecosystems": ["cosmos", "evm"]
}`

Then the filter in the component would be written similarly to the coin filter we currently have except checking list contents (only allowing filtering by one ecosystem at a time). What do you think?

**Comment by AlexBHarley** [comment]
Agreed, filtering by ecosystem makes more sense than a specific network. Would you classify `solana` as its own ecosystem? For example, $SUNNY was airdropped to Osmosis holders but the dapp is on Solana. 

Would you want to implement these changes? I think modifying the core JSON structure and then the filtering component is all that's needed.

**Comment by Callum-A** [comment]
@AlexBHarley Good point, I would class $SUNNY as Solana due to that being the chain it was built on. Maybe your example highlighted opens a new window to add an "eligible holders" (those who receive the airdrop) filter. A discussion for another time.

I'm happy to work on this change, if you wouldn't mind.

**Comment by AlexBHarley** [comment]
Definitely! So I think there's a few separate ideas here.

- Highlighting the ecosystem a token belongs to. This is useful because in the context of Cosmos, many networks just have one token so filtering is a bit of a pain
- More info on any given airdrop, maybe the table row expands when you click it to say who's eligible

**Comment by Callum-A** [comment]
Awesome I'll create a new issue for this second one so we don't lose track. I'll fork and get to work on the initial idea when I can.

**Comment by AlexBHarley** [comment]
Done with https://github.com/steakwallet/airdrops/pull/25
