### ISSUE TITLE
New Airdrop

### ISSUE THREAD

**Issue by Classmatetoken** [steakwallet/airdrops#78]
**Project**
SHIBA TADASHI

**Ecosystem**
What family of blockchains the project belongs to, e.g. Binance smart chain 

**Token Name**
Name of the token being airdropped, e.g. SHIBT

**Start Date**
01-20-2022

**End Date**
03-05-2022 (optional)

**Home Link**
Home page of the project, e.g. https://presale.shibatadashi.com

**Claim Link**
Link to website where you can claim or check your allocation, e.g.https://presale.shibatadashi.com

**Announcement Post**
Link to a website announcing the airdrop, e.g. https://t.me/Shibatadashi

**Comment by AlexBHarley** [comment]
For the following reasons, we won't be displaying this on the Steakwallet airdrops site.

- Specific wording around guaranteeing users infinite passive rewards
- Having to buy your way into the airdrop allocation.

Feel free to fork this website and merge your airdrop if you so desire.
